---
- name: install genisoimage
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  register: apt_status
  until: apt_status is success
  delay: 6
  retries: 10
  with_items:
    - genisoimage
  when: ansible_os_family == 'Debian'

- name: Create CD-ROM ISO with cloud-init config
  ansible.builtin.shell:
    cmd: >
      genisoimage -output {{ tempfilepath.path }}/{{ cloudinit_fqdn }}-cloudinit.iso -volid cidata -joliet -r
      {{ tempfilepath.path }}/meta-data {{ tempfilepath.path }}/network-config
      {{ tempfilepath.path }}/user-data {{ tempfilepath.path }}/vendor-data  &>> "{{ tempfilepath.path }}/logs"

- name: Copy ISO to target dir
  ansible.builtin.copy:
    remote_src: True
    src: "{{ tempfilepath.path }}/{{ cloudinit_fqdn }}-cloudinit.iso"
    dest: "{{ cloudinit_iso_dest_dir }}"
    owner: libvirt-qemu
    group: kvm
    mode: '0664'
...